### ISSUE TITLE
about aardio

### ISSUE THREAD

**Issue by GeofferyGeng** [zsj1029/MillionHero#1]
刚接触aardio，请问这个是不支持调用谷歌浏览器么？我想在运行的同时打开谷歌浏览器并搜索问题，但是失败了，如果支持，如何调用呢

**Comment by zsj1029** [comment]
支持的，跟语言无关，这个软件原理不需打开浏览器，直接走的百度搜索http请求，返回后数据做的筛选

**Comment by zsj1029** [comment]
[web.blink链接](http://bbs.aardio.com/forum.php?mod=viewthread&tid=22004&highlight=%E4%AF%C0%C0%C6%F7)
